/**
 * This file is part of the TREZOR project.
 *
 * Copyright (C) 2015 SatoshiLabs <info@satoshilabs.com>
 *           (C) 2014 Mike Tsao <mike@sowbug.com>
 *           (C) 2015 William Wolf <throughnothing@gmail.com>
 *
 * This library is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library.  If not, see <http://www.gnu.org/licenses/>.
 */

'use strict';
var send = require('./send');
var receive = require('./receive');


/**
 * Sends a message to Trezor and returns
 * an encoded message.
 * @param {Object} message Message from Trezor.js
 * @param {Object.<string, ProtoBuf.Builder.Message>} messages Builders, generated by reading config
 * @returns {Promise.<Object>} res Promise with object that can get directly send to trezor.js
 * @returns {Object} res.message Message as JSON
 * @returns {string} res.type Message name
 */
function call(message, messages) {

  var id = message.id;
  var type = message.type;
  var body = message.message;
  if (id == null) {
    throw new Error("Connection id is not defined.");
  }
  if (type == null) {
    throw new Error("Type is not defined");
  }
  //body can probably be null 
  return send(messages, id, type, body).then(function () {
    return receive(messages, id);
  });
}

module.exports = call;
